language: python

sudo: required
services:
  - docker

install:
  - docker build -f Dockerfile_old -t test-image .
  - docker ps -a

# Run tests
script:
  - docker run test-image scripts/test_code.sh

